### ISSUE TITLE
E185: Cannot find color scheme 'nord'

### ISSUE THREAD

**Issue by arambekverdyan** [bonop320/dotfiles#6]
in dotfiles dir I do:
stow vim
then
stow highlight

After thar when i try to open vim it causes the following message:

`Error detected while processing /home/aram/.vim/ui.vim:
line    7:
E185: Cannot find color scheme 'nord'
Error detected while processing /home/aram/.vim/plugins-config.vim:
line   59:
E117: Unknown function: denite#custom#var
Press ENTER or type command to continue`

**Comment by bonop320** [comment]
Nord theme should be installed automatically in queue with other plugins when you first start Vim. It may take a minute or so and requires internet connection.

Please check if you're connected to the internet and let me know if the problem persists.

**Comment by arambekverdyan** [comment]
The problem is solved after **cURL** installation
